version: "3"
services:
  portainer:
    image: portainer/portainer
    privileged: true
    volumes:
      - "./data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always

networks:
  default:
    external:
      name: scoobydoo
